// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdditeminvoicetestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void additeminvoicetest() {
    driver.get("http://localhost:4200/new-invoice");
    driver.manage().window().setSize(new Dimension(926, 1013));
    driver.findElement(By.id("mat-input-8")).sendKeys("1");
    driver.findElement(By.id("mat-input-8")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("mat-input-9")).sendKeys("4620010");
    driver.findElement(By.id("mat-input-9")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("mat-input-9")).sendKeys("4620010");
    driver.findElement(By.id("mat-input-10")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("mat-input-11")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("mat-input-9")).sendKeys("4620010");
    driver.findElement(By.id("mat-input-12")).sendKeys("50");
    driver.findElement(By.id("mat-input-12")).sendKeys(Keys.ENTER);
  }
}
