// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SaveinvoicedetailstestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void saveinvoicedetailstest() {
    driver.get("http://localhost:4200/new-invoice");
    driver.manage().window().setSize(new Dimension(926, 1013));
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("Test1");
    {
      WebElement element = driver.findElement(By.cssSelector("path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(2) > .mat-calendar-body-cell-content")).click();
    driver.findElement(By.cssSelector("#mat-select-value-1 > .mat-select-placeholder")).click();
    driver.findElement(By.cssSelector("#mat-option-1 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-value-3 > .mat-select-placeholder")).click();
    driver.findElement(By.cssSelector(".mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-value-5 > .mat-select-placeholder")).click();
    driver.findElement(By.cssSelector(".mat-option-text")).click();
    driver.findElement(By.id("mat-input-2")).click();
    driver.findElement(By.id("mat-input-2")).sendKeys("SWIFT 30 Days");
    driver.findElement(By.cssSelector(".mat-select-placeholder")).click();
    driver.findElement(By.cssSelector("#mat-option-10 > .mat-option-text")).click();
    driver.findElement(By.id("mat-input-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-focus-indicator:nth-child(12) > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-6")).sendKeys("200");
  }
}
